CREATE TABLE IF NOT EXISTS accounts(
  id VARCHAR(255) NOT NULL primary key COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  name varchar(255) COMMENT 'User Name',
  email varchar(255) UNIQUE COMMENT 'User Email',
  picture varchar(255) COMMENT 'User Picture'
) default charset utf8mb4 COMMENT '';


CREATE TABLE poem(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  title VARCHAR(255) NOT NULL,
  body VARCHAR(1000) NOT NULL,
  tags VARCHAR(255) NOT NULL,
  isArchived BOOLEAN NOT NULL,
  saves INT UNSIGNED NOT NULL DEFAULT 0,
  views INT UNSIGNED NOT NULL DEFAULT 0,
  likes INT UNSIGNED NOT NULL DEFAULT 0,
  authorId VARCHAR(255) NOT NULL,
  FOREIGN KEY (authorId) REFERENCES accounts (id) ON DELETE CASCADE
  -- FOREIGN KEY (saved) REFERENCES 
)

ALTER TABLE poem
ADD image varchar(255)


DROP TABLE poem;
INSERT INTO poem(title, body, tags, isArchived,  authorId) 
VALUES("A Coder’s Quiet Battle", "I.
", "Reflective", false,'66d109c1258b754bca428053'
 )

 CREATE TABLE savedPoem(
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
creatorId VARCHAR(255) NOT NULL,
poemId INT NOT NULL,
bookId INT NOT NULL,
FOREIGN KEY (creatorId) REFERENCES accounts (id) ON DELETE CASCADE,
FOREIGN KEY (poemId) REFERENCES poem (id) ON DELETE CASCADE,
FOREIGN KEY (bookId) REFERENCES books (id) ON DELETE CASCADE
 )

 DROP TABLE savedPoem

  CREATE TABLE likedPoem(
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
creatorId VARCHAR(255) NOT NULL,
poemId INT NOT NULL,
FOREIGN KEY (creatorId) REFERENCES accounts (id) ON DELETE CASCADE,
FOREIGN KEY (poemId) REFERENCES poem (id) ON DELETE CASCADE
 )

 CREATE TABLE books(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  title VARCHAR(255) NOT NULL,
  creatorId VARCHAR(255) NOT NULL,
  FOREIGN KEY (creatorId) REFERENCES accounts (id) ON DELETE CASCADE
 )